services:
  python-dev:
    build: .
    image: ${OWNER_NAME:-default}-python-dev:latest
    container_name: ${OWNER_NAME:-default}-python-dev-container
    ports:
      - "${SSH_PORT:-2222}:22"  # SSH port mapping from .env
    volumes:
      - ${HOST_WORK_DIR}:/workspace
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - SSH_USER=${SSH_USER}
      - SSH_PASSWORD=${SSH_PASSWORD}
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - app-net

networks:
  app-net:
    driver: bridge